-- 卸载脚本：删除工作流模块菜单 + 表单 schema 表 + Flowable 自带表（谨慎执行：会丢失全部流程数据）
DELETE FROM sys_role_menu WHERE menu_id IN (3001,3002,3003,3004,3005,3010,3011,3012,3013,3020,3021,3022,3023,3024,3025,3026,3027,3030,3031,3032,3033);
DELETE FROM sys_menu      WHERE menu_id IN (3001,3002,3003,3004,3005,3010,3011,3012,3013,3020,3021,3022,3023,3024,3025,3026,3027,3030,3031,3032,3033);

DROP TABLE IF EXISTS wf_form_schema;

-- Flowable 8 process 引擎核心表（按依赖顺序删）
DROP TABLE IF EXISTS ACT_HI_COMMENT;
DROP TABLE IF EXISTS ACT_HI_ATTACHMENT;
DROP TABLE IF EXISTS ACT_HI_DETAIL;
DROP TABLE IF EXISTS ACT_HI_VARINST;
DROP TABLE IF EXISTS ACT_HI_TASKINST;
DROP TABLE IF EXISTS ACT_HI_ACTINST;
DROP TABLE IF EXISTS ACT_HI_IDENTITYLINK;
DROP TABLE IF EXISTS ACT_HI_PROCINST;
DROP TABLE IF EXISTS ACT_RU_HISTORY_JOB;
DROP TABLE IF EXISTS ACT_RU_DEADLETTER_JOB;
DROP TABLE IF EXISTS ACT_RU_SUSPENDED_JOB;
DROP TABLE IF EXISTS ACT_RU_TIMER_JOB;
DROP TABLE IF EXISTS ACT_RU_JOB;
DROP TABLE IF EXISTS ACT_RU_EXTERNAL_JOB;
DROP TABLE IF EXISTS ACT_RU_VARIABLE;
DROP TABLE IF EXISTS ACT_RU_TASK;
DROP TABLE IF EXISTS ACT_RU_IDENTITYLINK;
DROP TABLE IF EXISTS ACT_RU_EVENT_SUBSCR;
DROP TABLE IF EXISTS ACT_RU_EXECUTION;
DROP TABLE IF EXISTS ACT_RU_ACTINST;
DROP TABLE IF EXISTS ACT_RU_ENTITYLINK;
DROP TABLE IF EXISTS ACT_HI_ENTITYLINK;
DROP TABLE IF EXISTS ACT_GE_BYTEARRAY;
DROP TABLE IF EXISTS ACT_RE_DEPLOYMENT;
DROP TABLE IF EXISTS ACT_RE_PROCDEF;
DROP TABLE IF EXISTS ACT_RE_MODEL;
DROP TABLE IF EXISTS ACT_PROCDEF_INFO;
DROP TABLE IF EXISTS ACT_GE_PROPERTY;
DROP TABLE IF EXISTS FLW_RU_BATCH;
DROP TABLE IF EXISTS FLW_RU_BATCH_PART;
DROP TABLE IF EXISTS FLW_EVENT_DEPLOYMENT;
DROP TABLE IF EXISTS FLW_EVENT_RESOURCE;
DROP TABLE IF EXISTS FLW_CHANNEL_DEFINITION;
DROP TABLE IF EXISTS FLW_EVENT_DEFINITION;
DROP TABLE IF EXISTS DATABASECHANGELOG;
DROP TABLE IF EXISTS DATABASECHANGELOGLOCK;
