-- 工作流增强：抄送 / 后加签 / 退回 三个按钮权限（与 3001 父菜单同 module）
-- changeset workflow-20260506-enhance-menu，由 module-workflow.yml 引用
INSERT INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (3023, '抄送', 3003, 4, '#', '', '', 1, 0, 'F', '0', '0', 'workflow:task:cc', '#', 'admin', NOW(), '', NULL, '');
INSERT INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (3024, '加签', 3003, 5, '#', '', '', 1, 0, 'F', '0', '0', 'workflow:task:addsign', '#', 'admin', NOW(), '', NULL, '');
INSERT INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (3025, '退回', 3003, 6, '#', '', '', 1, 0, 'F', '0', '0', 'workflow:task:sendback', '#', 'admin', NOW(), '', NULL, '');

-- 表单引擎按钮权限：表单查看 / 编辑 / 删除（与流程定义同列）
INSERT INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (3030, '表单设计', 3001, 5, 'form-designer', 'workflow/FormDesigner', 'processDefinitionKey=', 1, 0, 'C', '0', '0', 'workflow:form:list', 'form', 'admin', NOW(), '', NULL, '动态表单设计');
INSERT INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (3031, '查看', 3030, 1, '#', '', '', 1, 0, 'F', '0', '0', 'workflow:form:list', '#', 'admin', NOW(), '', NULL, '');
INSERT INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (3032, '编辑', 3030, 2, '#', '', '', 1, 0, 'F', '0', '0', 'workflow:form:edit', '#', 'admin', NOW(), '', NULL, '');
INSERT INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES (3033, '删除', 3030, 3, '#', '', '', 1, 0, 'F', '0', '0', 'workflow:form:remove', '#', 'admin', NOW(), '', NULL, '');
