import type { RouteRecordRaw } from 'vue-router'
import type { ScaffoldFrontendModule } from '../loader'
import formCreate from '@form-create/element-ui'

const routes: RouteRecordRaw[] = [
  {
    path: 'workflow/process',
    name: 'WorkflowProcessList',
    component: () => import('./views/ProcessList.vue'),
    meta: { title: '流程定义' }
  },
  {
    path: 'workflow/todo',
    name: 'WorkflowTodoList',
    component: () => import('./views/TodoList.vue'),
    meta: { title: '待办任务' }
  },
  {
    path: 'workflow/done',
    name: 'WorkflowDoneList',
    component: () => import('./views/DoneList.vue'),
    meta: { title: '已办任务' }
  },
  {
    path: 'workflow/designer',
    name: 'WorkflowDesigner',
    component: () => import('./views/Designer.vue'),
    meta: { title: '流程设计器' }
  },
  {
    path: 'workflow/form-designer',
    name: 'WorkflowFormDesigner',
    component: () => import('./views/FormDesigner.vue'),
    meta: { title: '表单设计' }
  },
  {
    path: 'workflow/instance-admin',
    name: 'WorkflowProcessAdmin',
    component: () => import('./views/ProcessAdmin.vue'),
    meta: { title: '实例管理' }
  }
]

const workflowModule: ScaffoldFrontendModule = {
  name: 'workflow',
  routes,
  locales: {
    'zh-CN': {
      workflow: {
        menu: {
          title: '工作流',
          process: '流程定义',
          todo: '待办任务',
          done: '已办任务',
          designer: '流程设计器',
          formDesigner: '表单设计',
          instanceAdmin: '实例管理'
        },
        common: {
          processInstance: '流程实例',
          processDefinition: '流程定义',
          businessKey: '业务 Key',
          businessKeyExample: '例如订单号',
          businessKeyExact: '精确匹配',
          definitionResource: '资源',
          deployTime: '部署时间',
          priority: '优先级',
          version: '版本',
          processKey: '流程 Key',
          taskName: '任务',
          processName: '流程',
          process: '流程',
          activityNode: '节点',
          variablesJson: '变量 (JSON)',
          comment: '说明',
          assignee: '加签人',
          assigneeHint: '加签的目标用户名',
          reason: '加签理由',
          actor: '操作人',
          deploy: '部署',
          start: '启动',
          view: '查看',
          form: '表单',
          progress: '进度',
          flowChart: '流程图',
          processChart: '流程图',
          timeline: '时间轴',
          stateRunning: '进行中',
          stateFinished: '已结束',
          stateAll: '全部',
          stateAllPlain: '全部',
          ended: '已结束',
          processProgress: '流程进度'
        },
        process: {
          searchPlaceholder: '按流程名搜索',
          deployBtn: '部署 BPMN',
          deployTitle: '部署 BPMN 流程',
          deployName: '部署名',
          deployNameHint: '可选，留空使用文件名',
          bpmnFile: 'BPMN 文件',
          pickBpmnTip: '请选择 BPMN 文件',
          pickedHint: '已选择：{name} ({size} KB)',
          startTitle: '启动流程',
          startName: '实例名',
          startNameHint: '可选',
          startForm: '启动表单',
          startNoSchema: '未配置启动表单 schema；可在"表单"按钮里设计后再回来启动。',
          xmlTitle: '流程图',
          deleteConfirm: '确认删除流程「{name}」（含已启动实例）？此操作不可恢复。',
          deleteOk: '已删除',
          deployOk: '部署成功',
          startOk: '已启动流程',
          dangerTitle: '危险操作',
          dangerConfirm: '确认删除',
          variablesInvalid: '变量必须是合法的 JSON 对象',
          formValidateFailed: '表单校验未通过',
          diffBtn: '版本对比',
          diffTitle: '版本对比：{name}',
          diffLeftVersion: '左侧版本',
          diffRightVersion: '右侧版本',
          diffPickPlaceholder: '请选择版本',
          diffNoVersions: '该流程没有可对比的版本',
          diffOnlyOne: '该流程仅有 1 个版本，无对比对象',
          diffSameVersion: '已选同一版本，请换一个',
          diffStatNoChange: '左右两版相同（按 BPMN 节点 id + name 计算）',
          diffStatChanged: '差异：{added} 增 / {removed} 删 / {renamed} 改名',
          diffMetaVersion: '版本',
          diffMetaDeployTime: '部署时间',
          diffMetaSuspended: '已挂起',
          diffMetaActive: '激活中',
          diffNodeAdded: '新增的节点',
          diffNodeRemoved: '删除的节点',
          diffNodeRenamed: '节点改名（id 相同 / name 不同）',
          diffEmptySection: '无',
          diffLoadFailed: '加载版本失败：{msg}',
          diffXmlFailed: '加载 BPMN XML 失败：{msg}'
        },
        todo: {
          taskNamePlaceholder: '按任务名搜索',
          actions: {
            handle: '处理',
            claim: '认领',
            delegate: '转办',
            cc: '抄送',
            addSign: '后加签',
            addSignBefore: '前加签',
            sendBack: '退回'
          },
          blocked: '被加签阻塞 ×{n}',
          blockedTitle: '被 {n} 个前加签子任务阻塞：{ids}',
          blockedHandle: '该任务被前加签阻塞，需等加签人完成后才能提交',
          blockedAddBefore: '已存在前加签子任务',
          handleTitle: '处理任务',
          handleComment: '审批意见',
          handleCommentHint: '（可选）填写审批意见，将作为评论保存',
          taskForm: '任务表单',
          schemaLoaded: '已加载表单 schema：{name}',
          schemaMissing: '未配置当前节点的任务表单 schema；可在「流程定义 → 表单」里指定 activityId={key} 后再回来。',
          completeBtn: '完成',
          completedOk: '已完成',
          claimedOk: '已认领',
          delegateTitle: '转办任务',
          delegatePrompt: '转办给（用户 ID 或用户名）',
          delegatedOk: '已转办',
          ccTitle: '抄送任务',
          ccReceivers: '抄送人',
          ccReceiversHint: '多个用户名以逗号分隔，例如：alice,bob',
          ccReceiversRequired: '至少填一个抄送人（用户名，逗号分隔）',
          ccCommentHint: '（可选）抄送说明，会一并出现在站内信里',
          ccBtn: '抄送',
          ccDoneCount: '已抄送 {n} 人',
          addSignTitle: '后加签',
          addSignAssigneeRequired: '请选择加签人',
          addSignDoneOk: '已后加签',
          addSignBeforeTitle: '前加签',
          addSignBeforeTip: '前加签：在当前任务之前插入审批人。当前任务会被标记为阻塞，必须在加签人完成后才能提交（仍由原 assignee 提交）。',
          addSignBeforeOk: '已前加签 — 当前任务将在加签人完成后才能提交',
          sendBackTitle: '退回任务',
          sendBackTarget: '目标节点',
          sendBackTargetHint: '留空 = 退回到上一个 userTask',
          sendBackReason: '退回理由',
          sendBackReasonHint: '必填，会进 task 评论与审计日志',
          sendBackReasonRequired: '请填写退回理由',
          sendBackOk: '已退回'
        },
        admin: {
          alertNonAdmin: '非管理员视角：仅显示由你发起的流程实例。',
          startUserId: '发起人 ID',
          startUser: '发起人',
          instanceId: '实例 ID',
          definitionsLoadFailed: '流程定义加载失败：{msg}',
          searchFailed: '查询流程实例失败：{msg}',
          cancelTitle: '取消流程实例',
          cancelPrompt: '确认取消实例 {id} ？请填写取消原因（会写入 Flowable history）：',
          cancelBtn: '取消实例',
          backBtn: '返回',
          cancelEnded: '已结束的实例无法取消',
          cancelOk: '已取消',
          cancelAction: '取消'
        },
        designer: {
          fileName: '文件名',
          deployName: '部署名',
          deployNameHint: '可选',
          importBtn: '导入',
          exportXml: '导出 XML',
          deployToEngine: '部署到引擎',
          deployOk: '部署成功'
        },
        formDesigner: {
          processPick: '选择流程定义',
          activityIdHint: '__START__ 启动表单',
          formStartLabel: '启动表单',
          formNameLabel: '表单名称',
          saveBtn: '保存为新版本',
          previewBtn: '打印 schema',
          reloadBtn: '重新加载',
          pickFirst: '请先选择流程定义',
          startFormSuffix: '（启动表单）',
          parseUserTaskFailed: '解析 BPMN userTask 失败：{msg}',
          schemaInvalidJson: '当前 schema 不是合法 JSON，加载为空模板',
          schemaLoadFailed: '加载表单 schema 失败：{msg}',
          schemaPickRequired: '请选择流程定义',
          savedAsNewVersion: '已保存为新版本（旧版本自动停用）',
          previewCount: 'schema 共 {n} 个组件，已打印到控制台'
        },
        progress: {
          dialogTitleFull: '流程进度 · {title}',
          dialogTitle: '流程进度',
          endedAt: '已结束 · {time}',
          activeAt: '进行中 · 当前 {ids}',
          rejectedAt: '已退回过：{ids}',
          legendCompleted: '已通过',
          legendActive: '当前',
          legendRejected: '退回过',
          exportSvg: '导出 SVG',
          notLoaded: '尚未加载流程图',
          printPdf: '打印 / 导出 PDF',
          printTip: '提示：在浏览器打印对话框中选择"另存为 PDF"。',
          emptyTimeline: '暂无时间轴数据',
          loadGraphFailed: '加载流程图失败：{msg}',
          loadTimelineFailed: '加载时间轴失败：{msg}',
          designerNotReady: '流程图尚未加载完成',
          svgEmpty: 'SVG 为空',
          exportSvgFailed: '导出 SVG 失败：{msg}',
          presignCancelTitle: '撤销前加签',
          presignCancelPrompt: '确认撤销前加签 → {name} ？\n撤销后该子任务将被删除，原任务将解除阻塞。',
          presignCancelBtn: '撤销',
          presignCancelOk: '已撤销前加签',
          presignCancelFailed: '撤销失败：{msg}',
          presignCancelled: '已撤销',
          timeline: {
            'process.start': '流程启动',
            'process.end': '流程结束',
            'activity.start': '节点到达',
            'activity.end': '节点结束',
            'task.complete': '任务完成',
            'task.cc': '抄送',
            'task.addsign.after': '后加签',
            'task.addsign.before': '前加签',
            'task.sendback': '退回',
            'task.comment': '评论'
          }
        }
      }
    },
    'en-US': {
      workflow: {
        menu: {
          title: 'Workflow',
          process: 'Definitions',
          todo: 'My todo',
          done: 'My done',
          designer: 'Designer',
          formDesigner: 'Form designer',
          instanceAdmin: 'Instances'
        },
        common: {
          processInstance: 'Process instance',
          processDefinition: 'Process definition',
          businessKey: 'Business key',
          businessKeyExample: 'e.g. order number',
          businessKeyExact: 'Exact match',
          definitionResource: 'Resource',
          deployTime: 'Deployed at',
          priority: 'Priority',
          version: 'Version',
          processKey: 'Process key',
          taskName: 'Task',
          processName: 'Process',
          process: 'Process',
          activityNode: 'Node',
          variablesJson: 'Variables (JSON)',
          comment: 'Comment',
          assignee: 'Assignee',
          assigneeHint: 'Username to add as assignee',
          reason: 'Reason',
          actor: 'Actor',
          deploy: 'Deploy',
          start: 'Start',
          view: 'View',
          form: 'Form',
          progress: 'Progress',
          flowChart: 'Process diagram',
          processChart: 'Process diagram',
          timeline: 'Timeline',
          stateRunning: 'Running',
          stateFinished: 'Finished',
          stateAll: 'All',
          stateAllPlain: 'All',
          ended: 'Ended',
          processProgress: 'Process progress'
        },
        process: {
          searchPlaceholder: 'Search by process name',
          deployBtn: 'Deploy BPMN',
          deployTitle: 'Deploy BPMN process',
          deployName: 'Deployment name',
          deployNameHint: 'Optional, file name will be used if blank',
          bpmnFile: 'BPMN file',
          pickBpmnTip: 'Please pick a BPMN file',
          pickedHint: 'Selected: {name} ({size} KB)',
          startTitle: 'Start process',
          startName: 'Instance name',
          startNameHint: 'Optional',
          startForm: 'Start form',
          startNoSchema: 'No start form schema. Design one via the "Form" button and come back.',
          xmlTitle: 'Process diagram',
          deleteConfirm: 'Are you sure you want to delete the process "{name}" (including running instances)? This is irreversible.',
          deleteOk: 'Deleted',
          deployOk: 'Deployed',
          startOk: 'Process started',
          dangerTitle: 'Dangerous operation',
          dangerConfirm: 'Confirm delete',
          variablesInvalid: 'Variables must be a valid JSON object',
          formValidateFailed: 'Form validation failed',
          diffBtn: 'Compare versions',
          diffTitle: 'Version diff: {name}',
          diffLeftVersion: 'Left version',
          diffRightVersion: 'Right version',
          diffPickPlaceholder: 'Pick a version',
          diffNoVersions: 'This process has no versions to compare',
          diffOnlyOne: 'Only 1 version exists; nothing to compare',
          diffSameVersion: 'Same version selected, please pick another',
          diffStatNoChange: 'Left and right are identical (by BPMN node id + name)',
          diffStatChanged: 'Diff: {added} added / {removed} removed / {renamed} renamed',
          diffMetaVersion: 'Version',
          diffMetaDeployTime: 'Deployed at',
          diffMetaSuspended: 'Suspended',
          diffMetaActive: 'Active',
          diffNodeAdded: 'Added nodes',
          diffNodeRemoved: 'Removed nodes',
          diffNodeRenamed: 'Renamed nodes (same id, different name)',
          diffEmptySection: '(none)',
          diffLoadFailed: 'Failed to load versions: {msg}',
          diffXmlFailed: 'Failed to load BPMN XML: {msg}'
        },
        todo: {
          taskNamePlaceholder: 'Search by task name',
          actions: {
            handle: 'Handle',
            claim: 'Claim',
            delegate: 'Delegate',
            cc: 'CC',
            addSign: 'Add (after)',
            addSignBefore: 'Add (before)',
            sendBack: 'Send back'
          },
          blocked: 'Blocked ×{n}',
          blockedTitle: 'Blocked by {n} pre-add-sign sub-task(s): {ids}',
          blockedHandle: 'This task is blocked by pre-add-sign and can be completed only after the assignee finishes.',
          blockedAddBefore: 'A pre-add-sign sub-task already exists',
          handleTitle: 'Handle task',
          handleComment: 'Comment',
          handleCommentHint: '(optional) Comment, will be saved as task comment',
          taskForm: 'Task form',
          schemaLoaded: 'Form schema loaded: {name}',
          schemaMissing: 'No task-level form schema configured for this node. Configure activityId={key} via "Process → Form" first.',
          completeBtn: 'Complete',
          completedOk: 'Completed',
          claimedOk: 'Claimed',
          delegateTitle: 'Delegate task',
          delegatePrompt: 'Delegate to (user ID or username)',
          delegatedOk: 'Delegated',
          ccTitle: 'CC task',
          ccReceivers: 'Receivers',
          ccReceiversHint: 'Multiple usernames comma-separated, e.g. alice,bob',
          ccReceiversRequired: 'At least one CC receiver (usernames, comma-separated)',
          ccCommentHint: '(optional) CC note, included in inbox notification',
          ccBtn: 'CC',
          ccDoneCount: 'CCed to {n} user(s)',
          addSignTitle: 'Add sign-off (after)',
          addSignAssigneeRequired: 'Please pick an assignee',
          addSignDoneOk: 'Added',
          addSignBeforeTitle: 'Add sign-off (before)',
          addSignBeforeTip: 'Pre-add-sign: insert an approver before the current task. The original task is marked as blocked and can only be completed after the inserted approver finishes (still completed by the original assignee).',
          addSignBeforeOk: 'Added (before) — current task is blocked until the new approver finishes',
          sendBackTitle: 'Send back task',
          sendBackTarget: 'Target node',
          sendBackTargetHint: 'Leave blank to send back to the previous userTask',
          sendBackReason: 'Reason',
          sendBackReasonHint: 'Required, will be saved as task comment + audit log',
          sendBackReasonRequired: 'Please fill in the reason',
          sendBackOk: 'Sent back'
        },
        admin: {
          alertNonAdmin: 'Non-admin view: only instances started by you are shown.',
          startUserId: 'Starter ID',
          startUser: 'Starter',
          instanceId: 'Instance ID',
          definitionsLoadFailed: 'Failed to load process definitions: {msg}',
          searchFailed: 'Failed to search instances: {msg}',
          cancelTitle: 'Cancel process instance',
          cancelPrompt: 'Cancel instance {id}? Please fill in a reason (will be written to Flowable history):',
          cancelBtn: 'Cancel',
          backBtn: 'Back',
          cancelEnded: 'Finished instances cannot be cancelled',
          cancelOk: 'Cancelled',
          cancelAction: 'Cancel'
        },
        designer: {
          fileName: 'File name',
          deployName: 'Deployment name',
          deployNameHint: 'Optional',
          importBtn: 'Import',
          exportXml: 'Export XML',
          deployToEngine: 'Deploy to engine',
          deployOk: 'Deployed'
        },
        formDesigner: {
          processPick: 'Pick process definition',
          activityIdHint: '__START__ start form',
          formStartLabel: 'Start form',
          formNameLabel: 'Form name',
          saveBtn: 'Save as new version',
          previewBtn: 'Print schema',
          reloadBtn: 'Reload',
          pickFirst: 'Please pick a process definition first',
          startFormSuffix: ' (start form)',
          parseUserTaskFailed: 'Failed to parse BPMN userTask: {msg}',
          schemaInvalidJson: 'Schema is not valid JSON, loaded as empty template',
          schemaLoadFailed: 'Failed to load form schema: {msg}',
          schemaPickRequired: 'Please pick a process definition',
          savedAsNewVersion: 'Saved as new version (old versions deactivated automatically)',
          previewCount: 'Schema has {n} component(s); printed to console'
        },
        progress: {
          dialogTitleFull: 'Process progress · {title}',
          dialogTitle: 'Process progress',
          endedAt: 'Ended · {time}',
          activeAt: 'Running · current {ids}',
          rejectedAt: 'Sent back: {ids}',
          legendCompleted: 'Completed',
          legendActive: 'Active',
          legendRejected: 'Rejected',
          exportSvg: 'Export SVG',
          notLoaded: 'Diagram not loaded yet',
          printPdf: 'Print / export PDF',
          printTip: 'Tip: pick "Save as PDF" in the print dialog.',
          emptyTimeline: 'No timeline data',
          loadGraphFailed: 'Failed to load diagram: {msg}',
          loadTimelineFailed: 'Failed to load timeline: {msg}',
          designerNotReady: 'Diagram is not ready yet',
          svgEmpty: 'SVG is empty',
          exportSvgFailed: 'Failed to export SVG: {msg}',
          presignCancelTitle: 'Cancel pre-add-sign',
          presignCancelPrompt: 'Cancel the pre-add-sign → {name}?\nThe sub-task will be deleted and the original task will be unblocked.',
          presignCancelBtn: 'Cancel',
          presignCancelOk: 'Pre-add-sign cancelled',
          presignCancelFailed: 'Cancel failed: {msg}',
          presignCancelled: 'Cancelled',
          timeline: {
            'process.start': 'Process started',
            'process.end': 'Process ended',
            'activity.start': 'Node arrived',
            'activity.end': 'Node ended',
            'task.complete': 'Task completed',
            'task.cc': 'CC',
            'task.addsign.after': 'Add (after)',
            'task.addsign.before': 'Add (before)',
            'task.sendback': 'Sent back',
            'task.comment': 'Comment'
          }
        }
      }
    }
  },
  install(ctx) {
    // 仅注册 runtime，让 <form-create> 在 TodoList / ProcessList 完成对话框里能直接渲染。
    // designer 走 defineAsyncComponent，仅在打开"表单设计"路由时才下载，避免主 bundle 暴涨 1MB+。
    ctx.app.use(formCreate)
  }
}

export default workflowModule
